### Find All
GET http://localhost:8080/api/content

### Find by Id
GET http://localhost:8080/api/content/2

### Create new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 3,
  "title": "My third blog",
  "description": "My third blog",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-14T21:20:40.7436762",
  "dateUpdated": null,
  "url": ""
}

### Update content
PUT http://localhost:8080/api/content/3
Content-Type: application/json

{
  "id": 3,
  "title": "My third blog",
  "description": "My third blog",
  "status": "IN_PROGRESS",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-14T21:20:40.7436762",
  "dateUpdated": "2023-08-14T21:31:40.7436762",
  "url": "http://localhost:8080/my-third-blog"
}

### Delete content
DELETE http://localhost:8080/api/content/3